
--- Tabela SOLICITAÇÕES ----

CREATE TABLE SOLICITACOES
   (NUMERO_SOLICITACAO integer, 
	STATUS_SD VARCHAR2(12), 
	NUMERO_DO_DOCUMENTO NUMBER(12,0), 
	SITUACAO_DO_DOCUMENTO VARCHAR2(1), 
	DRAZAOSOCIL VARCHAR2(150), 
	BAIRRO VARCHAR2(80), 
	CEP VARCHAR2(8), 
	MUNICIPIO VARCHAR2(60), 
	DCNAE VARCHAR2(256), 
	REGIONAL integer, 
	VALIDADE_DOCUMENTO DATE
   ) ;
   