ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

ALTER  USER FATEC_OP IDENTIFIED BY Senha123
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
PROFILE DEFAULT
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO FATEC_OP;


SELECT * FROM ALL_TABLES;

SELECT * FROM USER_TABLES;