ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER FATEC_OP IDENTIFIED BY FatecOracle1234
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
PROFILE DEFAULT
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO FATEC_OP;