--- CRIAR TABELA EMPREGADO

CREATE TABLE EMP (
EMPNO NUMBER CONSTRAINT PK_EMP PRIMARY KEY,
ENAME VARCHAR2(10) CONSTRAINT NN_ENAME NOT NULL CONSTRAINT UPPER_NAME
CHECK (ENAME = UPPER(ENAME)),
JOB VARCHAR2(9),
MGR NUMBER CONSTRAINT FK_MGR REFERENCES EMP(EMPNO),
HIREDATE DATE DEFAULT (SYSDATE),
SAL NUMBER(10,
2) CONSTRAINT CK_SAL CHECK (SAL > 500),
COMM NUMBER(9,
0) DEFAULT NULL,
DEPTNO NUMBER(2));

ALTER TABLE EMP MODIFY JOB VARCHAR(30);