SELECT TABLE_NAME 
  FROM USER_TABLES;
  
  
  SELECT * FROM COMERCIAL.PEDIDO;
  SELECT * FROM COMERCIAL.PRODUTO;
  SELECT * FROM COMERCIAL.CLIENTE;
  SELECT * FROM COMERCIAL.COR;
  
  --   FROM 	TERCEIRIZADO T INNER JOIN SETOR S ON T.CODSETOR IN S.CODSETOR;
  
  -- 1)	ESCREVA UMA CONSULTA QUE APRESENTE O NOME DO CLIENTE, A DESCRIÇÃO DO PRODUTO E A QUANTIDADE PEDIDA POR ORDEM DE CLIENTE E PRODUTO. 
  
  SELECT DISTINCT C.EMPRESA, R.DESCRICAO, P.QUANT 
  FROM COMERCIAL.CLIENTE C 
  INNER JOIN COMERCIAL.PEDIDO P ON C.CODCLI IN P.CODCLI 
  INNER JOIN COMERCIAL.PRODUTO R ON  P.CODPROD IN R.CODPROD
  ORDER BY C.EMPRESA, P.QUANT;
  
  -- 2)	ESCREVA UMA CONSULTA QUE APRESENTE A DESCRIÇÃO DO PRODUTO, A COR DO PRODUTO E A QUANTIDADE PEDIDA APENAS DO CLIENTE QUE TENHA COMO CONTATO O SR. CARLOS DE ANDRADE.
  
 SELECT DISTINCT CL.CONTATO ,PR.DESCRICAO, CR.DESCRICAO AS COR
    FROM COMERCIAL.CLIENTE CL LEFT JOIN COMERCIAL.PEDIDO PD 
        ON CL.CODCLI IN PD.CODCLI 
        INNER JOIN COMERCIAL.PRODUTO PR 
        ON PD.CODPROD IN PR.CODPROD RIGHT JOIN COMERCIAL.COR CR ON PR.CODCOR IN CR.CODCOR
        WHERE CL.CONTATO = 'CARLOS DE ANDRADE'
  ;
  
   -- 3)	Escreva uma consulta que apresente o Código do pedido, 
   --       data do pedido e nome de todos os clientes independente se tenha ou não pedidos registrados para um determinado cliente.
   
   
   
  SELECT DISTINCT PD.CODIGO, PD.DATA, CL.EMPRESA
    FROM COMERCIAL.CLIENTE CL FULL OUTER JOIN COMERCIAL.PEDIDO PD 
    ON CL.CODCLI IN PD.CODCLI 
;

-- 4)	Liste todas as cores e os produtos que às utilizam independente se algum produto usa ou não uma determinada cor. 
--      Coloque em ordem crescente do nome do produto
   
   
    SELECT DISTINCT CR.DESCRICAO AS COR, PR.DESCRICAO
    FROM COMERCIAL.PRODUTO PR RIGHT JOIN COMERCIAL.COR CR ON PR.CODPROD IN  CR.CODCOR
    ORDER BY PR.DESCRICAO ASC;

   
   
   
   
   
   
   
   