
CREATE OR REPLACE  PROCEDURE MUDA_SALARIO
 AS 
  V_DATA_MUDANCA DATE;
 
 BEGIN
    UPDATE EMP
	   SET SAL = SAL + 100
	  WHERE JOB = 'VENDEDOR';
	  
	UPDATE EMP 
	   SET SAL = SAL + 50
	   WHERE JOB = 'TECNICO';
	
	UPDATE EMP
	   SET SAL = SAL + 80
	  WHERE JOB = 'ANALISTA';
	  
	  SELECT SYSDATE INTO V_DATA_MUDANCA FROM DUAL;
      DBMS_OUTPUT.PUT_LINE(TO_CHAR(V_DATA_MUDANCA));
 END;
 