SET ECHO ON;
SET LINESIZE 1000;
SET SERVEROUTPUT ON;


TRUNCATE TABLE TAB_ANALISA_AUMENTO;
SELECT '--- INICIO DA ROTINA PL/SQL ---' FROM DUAL;

DECLARE
   V_EMPNO    EMP.EMPNO%TYPE;
   V_NOME     EMP.ENAME%TYPE;
   V_JOB      EMP.JOB%TYPE;
   V_SAL      EMP.SAL%TYPE;
   V_COMM      EMP.COMM%TYPE;

  BEGIN
     FOR DADOS_EMP IN
        (SELECT DISTINCT EMPNO, ENAME, JOB, SAL, COMM FROM EMP )
	  LOOP
	      V_EMPNO := DADOS_EMP.EMPNO;
          V_NOME := DADOS_EMP.ENAME;
          V_JOB := DADOS_EMP.JOB;
		  V_SAL := DADOS_EMP.SAL;
		  V_COMM := DADOS_EMP.COMM;
            IF V_JOB = 'BALCONISTA' AND V_SAL < 1000
		       THEN
			      INSERT INTO TAB_ANALISA_AUMENTO (EMPNO, ENAME, JOB, SAL, COMM) VALUES (V_EMPNO, V_NOME, V_JOB, V_SAL, V_COMM);
		    END IF;
        END LOOP;
     
	 COMMIT;
   
 END;
 /
 