
ALTER TABLE CLIENTE_EX
ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (CODIGO_CLIENTE);

ALTER TABLE CIDADES
ADD CONSTRAINT PK_CIDADE
PRIMARY KEY (CODIGO_CIDADE);

ALTER TABLE VENDEDORES
ADD CONSTRAINT PK_VENDEDOR
PRIMARY KEY (CODIGO_VENDEDOR);

ALTER TABLE VENDAS
ADD CONSTRAINT PK_VENDA
PRIMARY KEY (CODIGO);

ALTER TABLE PRODUTO_EX
ADD CONSTRAINT PK_PRODUTO
PRIMARY KEY (CODIGO_PRODUTO);


--FOREIGN KEYS
ALTER TABLE VENDAS
ADD CONSTRAINT FK_CLIENTE
FOREIGN KEY (CODIGO_CLIENTE)
REFERENCES CLIENTE_EX(CODIGO_CLIENTE);

ALTER TABLE VENDAS
ADD CONSTRAINT FK_PRODUTO
FOREIGN KEY (CODIGO_PRODUTO)
REFERENCES PRODUTO_EX(CODIGO_PRODUTO);
--DEU ERRADO

ALTER TABLE VENDAS
ADD CONSTRAINT FK_CIDADE
FOREIGN KEY (CODIGO_CIDADE)
REFERENCES CIDADES(CODIGO_CIDADE);

ALTER TABLE VENDAS
ADD CONSTRAINT FK_VENDEDOR
FOREIGN KEY (CODIGO_VENDEDOR)
REFERENCES VENDEDORES(CODIGO_VENDEDOR);


















