SELECT ENAME, JOB, SAL AS SALARIO_ATUAL,
CASE
WHEN JOB = 'VENDEDOR' THEN SAL * 3 
WHEN JOB = 'CAIXA' THEN SAL * 3 
END AS SALARIO_TRIPLO
FROM EMP;

SELECT INITCAP(ENAME), UPPER(JOB), SAL AS SALARIO_ATUAL,
CASE
WHEN UPPER(JOB) = 'VENDEDOR' THEN SAL * 3 
WHEN UPPER(JOB) = 'CAIXA' THEN SAL * 3 
    ELSE SAL
END AS SALARIO_TRIPLO
FROM EMP;

SELECT INITCAP(ENAME), UPPER(JOB), SAL AS SALARIO_ATUAL,
CASE
WHEN UPPER(JOB) = 'VENDEDOR' THEN SAL * 3 
WHEN UPPER(JOB) = 'CAIXA' THEN SAL * 3 
WHEN (SAL * 5)/2 > 500 THEN SAL * 3
    ELSE SAL
END AS SALARIO_TRIPLO
FROM EMP;

SELECT INITCAP(ENAME), UPPER(JOB), SAL AS SALARIO_ATUAL,
CASE
WHEN UPPER(JOB) = 'VENDEDOR' THEN SAL * 1.2 
WHEN UPPER(JOB) = 'CAIXA' THEN SAL * 1.1 
WHEN (SAL * 5)/2 > 500 THEN SAL * 1.05
    ELSE SAL * 1.01
END AS NOVO_SALARIO
FROM EMP;

SELECT CUST_FIRST_NAME, CUST_LAST_NAME,
CASE 
	WHEN UPPER(CUST_MARITAL_STATUS) = 'MARRIED' THEN 'CASADO'
    WHEN UPPER(CUST_MARITAL_STATUS) = 'SINGLE' THEN 'SOLTEIRO'
    WHEN UPPER(CUST_MARITAL_STATUS) IS NULL THEN 'INDEFINIDO'
END AS ESTADO_CIVIL,
CASE
    WHEN UPPER(CUST_VALID) = 'I' THEN 'INATIVO'
    WHEN UPPER(CUST_VALID) = 'A' THEN 'ATIVO'
    END AS STATUS
FROM SH.CUSTOMERS;

SELECT * FROM EMP;

SELECT DEPTNO, UPPER(JOB), SUM(SAL)  AS TOT_SAL FROM EMP 
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, UPPER(JOB), SUM(SAL)  AS TOT_SAL FROM EMP 
GROUP BY ROLLUP  (DEPTNO, JOB)
ORDER BY DEPTNO, JOB;


-- Group By / Rollup
select * from vendas;
select * from cidade;
select * from vendedores_ex;
select * from cliente_ex;
select * from produto_ex;

SELECT 
  C.CIDADES, 
  PRX.PRODUTOS, 
  sum (V.VOLUME_VENDA) AS TOTVOLUME_VENDAS
FROM 
  CIDADE C
  INNER JOIN VENDAS V ON C.CODIGO_CIDADE = V.CODIGO_CIDADE 
  INNER JOIN PRODUTO_EX PRX ON V.CODIGO_PRODUTO = PRX.CODIGO_PRODUTO
GROUP BY 
  ROLLUP(C.CIDADES, PRX.PRODUTOS)
  order by C.CIDADES;