--		FAÇA AS QUERYS SOBRE O SCHEMA VENDAS RESPONDENDO AS SEGUINTES PERGUNTAS:
--		
--		1--- ACHE O PREÇO MEDIO DE VENDA POR CIDADE (MOSTRANDO O NOME DA CIDADE)
--		
--		2--- ACHE O VOLUME TOTAL DE VENDA DE CADA PRODUTO (MOSTRANDO O NOME DO PRODUTO)
--		DA CIDADE DE SOROCABA
--		
--		3--- ACHE O VALOR TOTAL QUE CADA VENDEDOR VENDEU POR PRODUTO ORDENADO
--		POR VENDEDOR E PRODUTO
--		
--		4--- ACHE O VOLUME TOTAL DE VENDA DE CADA VENDEDOR DE CADA PRODUTO
--		QUE ELE VENDEU ORDENADO PELO NOME DO VENDEDOR E VOLUME DE VENDA ONDE
--		  VOLUME TOTAL MAIOR 5000 E MENOR QUE  7000
--		
--		5--- ACHE O VALOR TOTAL DE VENDA POR PRODUTO(MOSTRAR PRODUTO),
--		POR CIDADE (MOSTRAR CIDADE) E CLIENTE ORDENADO POR PRODUTO, TOTAL DA VENDA E CIDADE

select v.* from vendas v;
select vx.* from vendedores_ex vx;
select c.* from cidade c;

select c.cidades, round(avg(v.PRECO_VENDA),2) as Media from cidade c inner join vendas v on c.codigo_cidade = v.CODIGO_CIDADE
group by c.cidades, v.PRECO_VENDA;
