
CREATE TABLE DADOS_SOLICITACAO_TOTAL AS SELECT * FROM ALUNOGERAL_01.DADOS_SOLICITACAO_TOTAL;

CREATE TABLE BAIRRO AS SELECT * FROM ALUNOGERAL_01.BAIRRO;

------------------ TESTE 01 -----------------------
SELECT DADOS_SOLICITACAO_TOTAL.COD_EMPRESA,   DADOS_SOLICITACAO_TOTAL.RAZAO_SOCIAL,
  DADOS_SOLICITACAO_TOTAL.SITUACAO_EMPRESA,   DADOS_SOLICITACAO_TOTAL.LOGRADOURO,
  DADOS_SOLICITACAO_TOTAL.BAIRRO,   DADOS_SOLICITACAO_TOTAL.COD_ATIVIDADE,
  DADOS_SOLICITACAO_TOTAL.ATIVIDADE,   DADOS_SOLICITACAO_TOTAL.CEP,
  DADOS_SOLICITACAO_TOTAL.MUNICIPIO,   DADOS_SOLICITACAO_TOTAL.CNPJ_CPF,  BAIRRO.COD_BAIRRO
FROM DADOS_SOLICITACAO_TOTAL INNER JOIN BAIRRO
  ON DADOS_SOLICITACAO_TOTAL.BAIRRO = BAIRRO.BAIRRO
    WHERE  DADOS_SOLICITACAO_TOTAL.BAIRRO = 'ZONA RURAL';
    
---- CREATE INDEX INDX_BAIRRO ON DADOS_SOLICITACAO_TOTAL(BAIRRO);

 ANALYZE TABLE DADOS_SOLICITACAO_TOTAL ESTIMATE STATISTICS;
 
 ------------ TESTE 02 -------------------------------------------
 SELECT nomedomunicipio, NOMEDAEMPRESA, ENDERECO, "DATA"
    FROM municipios  INNER JOIN empresas 
ON empresas.codigodomunicipio = municipios.codigodomunicipio
  INNER JOIN RECLAMACOES 
 ON empresas.CODIGODAEMPRESA = RECLAMACOES.CODIGODAEMPRESA
  WHERE nomedomunicipio = 'MARILIA';
  
---  ---- COM ÍNDICE ------------

CREATE INDEX INDX01_MUNICIPIO  ON MUNICIPIOS (nomedomunicipio);
  
  ANALYZE table MUNICIPIOS estimate statistics;
  
  