---- Script com exemplos usando Operações de Algebra Relacional 
---- União, Intersecção, Diferença
 
--- Cria uma cópia da Tabela
 CREATE TABLE EMPREGADO_REGIONAL AS SELECT * FROM FATEC_OP.EMPREGADO_REGIONAL;

 CREATE TABLE USUARIO_AREA1 AS SELECT * FROM FATEC_OP.USUARIO_AREA1 ;
 
 CREATE TABLE USUARIO_AREA2 AS SELECT * FROM FATEC_OP.USUARIO_AREA2 ;
 
 ----- Usando LIKE
  SELECT * FROM EMPREGADO_REGIONAL WHERE EMPREGADO LIKE '%SILVA%';
  
  SELECT REGIONAL, EMPREGADO FROM EMPREGADO_REGIONAL 
    WHERE EMPREGADO NOT LIKE '%SILVA%';
----
--- NÃO TRAZ DUPLICADAS
SELECT * FROM FATEC_OP.USUARIO_AREA1 
UNION 
 SELECT * FROM FATEC_OP.USUARIO_AREA2; 
 
 --- TRAZ DUPLICADAS
 SELECT * FROM FATEC_OP.USUARIO_AREA1 
UNION ALL
 SELECT * FROM FATEC_OP.USUARIO_AREA2;

 ----
 SELECT COUNT(*) FROM USUARIO_AREA1;
  SELECT COUNT(*) FROM USUARIO_AREA2;
  
 ---- DIFERENÇA 
  SELECT * FROM FATEC_OP.USUARIO_AREA1 
    MINUS
 SELECT * FROM FATEC_OP.USUARIO_AREA2;
 
 ---- Intersecção
 SELECT * FROM FATEC_OP.USUARIO_AREA1 
    INTERSECT
 SELECT * FROM FATEC_OP.USUARIO_AREA2;
 ------
 
 SELECT * FROM USUARIO_AREA1 
 WHERE REGISTRO NOT IN (SELECT REGISTRO FROM USUARIO_AREA2);
 
 
 
 
 
 
 
 
 
 
 
  