PROMPT INSERTING INTO SETOR s 
 
Insert into SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) values ('200','COMÈRCIO DE PLÁSTICO','20');
Insert into SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) values ('210','COMÉRCIO DE IMPORTADOS','20');
Insert into SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) values ('310','MAQUINÁRIO','10');
Insert into SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) values ('320','COMPRESSORES','10');
Insert into SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) values ('330','METAIS PESADOS','10');
insert into SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) values ('340','INJETORES','10');
Insert into SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) values ('230','COMÉRCIO EXTERIOR','20');
Insert into SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) values ('350','POLÍMEROS','10');
Insert into SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) values ('400','CONTAS A PAGAR','30');
Insert into SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) values ('410','CONTABILIDADE','30');
Insert into SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) values ('300','TUBOS METÁLICCOS','10');

COMMIT;
