INSERT INTO SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) VALUES ('200','COMÉRCIO DE PLÁSTICO','20');
INSERT INTO SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) VALUES ('210','COMÉRCIO DE IMPORTADOS','20');
INSERT INTO SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) VALUES ('310','MAQUINÁRIO','10');
INSERT INTO SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) VALUES ('320','COMPRESSORES','10');
INSERT INTO SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) VALUES ('330','METAIS PESADOS','10');
INSERT INTO SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) VALUES ('340','INJETORES','10');
INSERT INTO SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) VALUES ('230','COMÉRCIO EXTERIOR','20');
INSERT INTO SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) VALUES ('350','POLÍMEROS','10');
INSERT INTO SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) VALUES ('400','CONTAS A PAGAR','30');
INSERT INTO SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) VALUES ('410','CONTABILIDADE','30');
INSERT INTO SETOR (CODSETOR,DESC_SETOR,AREA_CODIGO) VALUES ('300','TUBOS METÁLICCOS','10');

COMMIT;

