
SET DEFINE OFF;
Insert into TERCEIRIZADO (COD_TERCEIRO,NOME_COLABORADOR,CODSETOR) values ('78','JUNIOR GOMES','210');
Insert into TERCEIRIZADO (COD_TERCEIRO,NOME_COLABORADOR,CODSETOR) values ('56','HELENA HENRIQUE SILVA','300');
Insert into TERCEIRIZADO (COD_TERCEIRO,NOME_COLABORADOR,CODSETOR) values ('23','OCTAVIO RODRIGUES SILVA','200');
Insert into TERCEIRIZADO (COD_TERCEIRO,NOME_COLABORADOR,CODSETOR) values ('14','ANTONIO CONRRADO PENTES','400');
Insert into TERCEIRIZADO (COD_TERCEIRO,NOME_COLABORADOR,CODSETOR) values ('54','MENDOÇA METIDO','400');
Insert into TERCEIRIZADO (COD_TERCEIRO,NOME_COLABORADOR,CODSETOR) values ('25','LAURA JOSE ANDRADA','310');
Insert into TERCEIRIZADO (COD_TERCEIRO,NOME_COLABORADOR,CODSETOR) values ('31','PIRES APARECIDO CUNHA','320');
Insert into TERCEIRIZADO (COD_TERCEIRO,NOME_COLABORADOR,CODSETOR) values ('19','ULIANA PIMENTA',null);
Insert into TERCEIRIZADO (COD_TERCEIRO,NOME_COLABORADOR,CODSETOR) values ('27','SANDRA HATILIO PRADO',null);

