alter session set "_ORACLE_SCRIPT" = true;

CREATE USER FATEC IDENTIFIED BY L30n4rd0_ 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
PROFILE DEFAULT
	QUOTA UNLIMITED ON USERS;

--- PERMISSÕES
GRANT CONNECT, RESOURCE TO FATEC;
