ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

ALTER USER FATEC_OP IDENTIFIED BY Le0n4rd0_
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
PROFILE DEFAULT
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO FATEC_OP;
