alter session set "_ORACLE_SCRIPT" = true;

CREATE USER ALUNO_RA IDENTIFIED BY TESTE 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
PROFILE DEFAULT
	QUOTA UNLIMITED ON USERS;

--- PERMISSÕES
GRANT CONNECT, RESOURCE TO IGOR_REVISAO;
